jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    #example: site/job
    path('', views.index, name='index'),
    path('redirect', views.redirect_user, name='redirect_user'),
    path('thank_you', views.thank_you, name='thank_you'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('customer-register', include('customer_register.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('jobs-admin/', include('jobs_admin.urls')),
    path('addjob/', include('addjob.urls')),
    path('expenses/', include('expenses.urls')),
    path('add-payment/', include('add_payment.urls')),
    path('payment-history/', include('payment_history.urls')),
    path('payments/', include('payment_requests.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('add-house/', include('add_house.urls')),
    path('add-expense/', include('add_expense.urls')),
    path('spreadsheets/', include('csv_generator.urls')),
    path('projects/', include('projects.urls')),
    path('search/', include('search_submit.urls')),
    path('send-data/', include('send_data.urls')),
    path('project-details/', include('project_details.urls')),
    path('customer-payments/', include('customer_payments.urls')),
    path('property/', include('property.urls')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('tenants/', include('tenants.urls')),
    path('leads/', include('leads.urls')),
    path('redirect/', include('redirect.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenants/urls.py
from django.urls import path
from .views import (
    TenantListView,
    TenantCreateView,
    TenantDeleteView,
    ProcessSendMassMessageForm,
)

app_name = 'tenants'

urlpatterns = [
    path('', TenantListView.as_view(), name='list_tenants'),
    path('add-tenant', TenantCreateView.as_view(), name='add_tenant'),
    path('delete-tenant', TenantDeleteView.as_view(), name='delete_tenant'),
    path('send-mass-message', ProcessSendMassMessageForm.as_view(), name='send_mass_message'),
]

tenants/models.py
from django.db import models
from property.models import Company
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

class Tenant(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=150)
    phone_number = PhoneNumberField(null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    email = models.EmailField(null=True)
    lease_begin = models.DateField()
    lease_length = models.IntegerField(default=12) # In months

    def __str__(self):
        return 'Tenant #{0} - {1} - {2}'.format(self.pk, self.name, self.company.name)

    def get_absolute_url(self):
        return reverse('tenants:add_tenant') + '?c=' + str(self.company.id)

    @property
    def lease_end(self):
        # Calculates the end date of the lease
        # Returns: Date object
        return self.lease_begin + relativedelta(months=+self.lease_length)

    @property
    def ending_soon(self):
        # If the lease end date is within 90 days from now, returns true else returns false
        # Returns: Boolean

        # Get current date
        date_now = datetime.now().date()
        date_difference = self.lease_end - date_now
        return date_difference.days <= 90

tenants/forms.py
from django import forms
from .models import Tenant
from django.views.generic.edit import CreateView
from django.utils.translation import gettext as _

class TenantFormCreate(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        """Checks if lease length is a positive integer"""

        # Call clean method from base class first
        cleaned_data = super().clean()
        lease_length = cleaned_data.get('lease_length')
        print(type(lease_length))

        # If lease length is less than or equal to zero, raise an error
        if lease_length <= 0:
            message = 'Please choose a number larger than zero for lease length.'
            raise forms.ValidationError(_(message), 'invalid_input')

        return cleaned_data

    lease_begin = forms.DateTimeField(
        input_formats=['%m/%d/%Y'],
        widget=forms.TextInput(attrs={'onkeydown':'return false', 'readonly': 'true'}),
    )

    class Meta:
        model = Tenant
        fields = ['name', 'phone_number', 'email', 'lease_begin', 'lease_length']

class TenantMassMessage(forms.Form):
    message = forms.CharField(label='Message', max_length=1000, widget=forms.Textarea)

tenants/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .models import Tenant
from property.models import Company
from customer_register.models import Customer_User
from .forms import TenantFormCreate, TenantMassMessage
from django.views import View
from django.http import Http404, HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from twilio.rest import Client

def dispatch(class_name, class_instance, request, *args, **kwargs):
    # Check if there is a GET variable if not redirect to the home page
    try:
        company_id = int(request.GET.get('c', None))
    except ValueError:
        # Customer id was empty in GET variable
        raise Http404('Company not found!')
    except TypeError:
        # No GET variables attached to url
        raise Http404('Invalid url!')

    # Get the company
    company = None
    try:
        company = Company.objects.get(id=company_id)
    except Company.DoesNotExist:
        # Company id was in GET variable but NOT found in database
        raise Http404('Company not found!')

    customer_id = company.customer_user.id
    if not request.user.is_superuser: # Will raise 'User object has no customer_user object if superuser'
        if request.user.is_authenticated and request.user.customer_user.id != customer_id:
            # Do not allow the customer_user (if they are logged in) to make appointments for other customers calendars
            raise PermissionDenied('Request denied!')

    return super(class_name, class_instance).dispatch(request, args, kwargs)

class TenantListView(LoginRequiredMixin, ListView):
    """Shows users a list of tenants"""
    paginate_by = 25

    def get_queryset(self):
        # Filter objects by user's companies
        company_id = int(self.request.GET.get('c', None))
        company = Company.objects.get(pk=company_id)
        return Tenant.objects.filter(
            company=company,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fields
        context['fields'] = ('Name', 'Phone Number', 'Email', 'Lease Begin', 'Lease End')
        context['customer_user'] = self.request.user.customer_user

        # Company object
        company_id = int(self.request.GET.get('c', None))
        company = Company.objects.get(pk=company_id)

        context['tenant_mass_message_form'] = TenantMassMessage()
        context['company'] = company

        return context

    def dispatch(self, request, *args, **kwargs):
        return dispatch(TenantListView, self, request, args, kwargs)

class ProcessSendMassMessageForm(View):
    # Handle the submission of the send mass message form
    success_message = 'Message sent successfully!'
    def post(self, request, *args, **kwargs):
        send_text_message = request.POST.get('send_text_message', None)
        message = request.POST.get('message', None)
        company_id = request.POST.get('company_id', None)

        # Get ALL tenants belonging to the company
        company = Company.objects.get(pk=int(company_id))
        tenants = Tenant.objects.filter(company=company)

        if send_text_message == 'True':
            # Send text message to ALL tenants
            client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)

            for tenant in tenants:
                client.messages.create(
                    body=message,
                    to=tenant.phone_number.as_e164,
                    from_=settings.TWILIO_NUMBER,
                )
        else:
            # Send email to tenants
            pass

        return HttpResponse('/tenants')


class TenantCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Allows user to add tenants"""

    model = Tenant
    form_class = TenantFormCreate
    template_name = 'tenants/add_tenant_form.html'
    success_message = 'Tenant successfully added.'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request # Pass request object to form when it is initialized
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['customer_user'] = self.request.user.customer_user
        return context

    def form_valid(self, form):
        # Set company for tenant based on the GET parameters in the url
        company_id = self.request.GET.get('c', None)
        company = Company.objects.get(id=int(company_id))

        tenant = form.save(commit=False) # Call form.save(commit=False) to create an object 'in memory' and not in the database
        tenant.company = company
        tenant.save()

        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        return dispatch(TenantCreateView, self, request, args, kwargs)

class TenantDeleteView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        # Handle POST requests to this view
        if 'object_id' in request.POST:
            tenant_id = int(self.request.POST.get('object_id'))
            tenant = Tenant.objects.get(pk=tenant_id)

            # Get updated company disabled_datetime objects and send as a string to the ajax success function
            tenants = Tenant.objects.filter(company=tenant.company)
            context = {
                'object_list': tenants,
                'fields': ('Name', 'Phone Number', 'Email', 'Lease Begin', 'Lease End'),
                'csrf_token': request.POST.get('csrfmiddlewaretoken')
            }

            # Delete the selected object
            tenant.delete()
            html_response = ''
            if not tenants.exists():
                html_response = '<p style="text-align: center;">There are currently no tenants.</p>'
            else:
                html_response = render_to_string('tenants/tenant_list_ajax_results.html', context)

            return HttpResponse(html_response)
        else:
            return JsonResponse({'error': 'Invalid post request'}, status=400)

tenants/templates/tenants/add_tenant_form.html
{% extends 'base_appointment.html' %}

{% load static %}
{% load bootstrap_tags %}

{% block title %}Add Tenant{% endblock title %}
{% block scripts %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
{% endblock scripts %}

{% block content %}
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1 id="appointment-title">
          {% if not object.pk %}
            Add Tenant
          {% else %}
            Edit Tenant
          {% endif %}
          </h1>
          <p id="appointment-description">
            Add your tenant by filling out the form below.
          </p>
      </div>

      <form class="form-horizontal" method="post">
        {% csrf_token %}
        {# Non Field Form Errors #}
        {% if form.errors %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
        {% endif %}

        {{ form.name.errors }}
        {{ form.name.label_tag }}
        {{ form.name }}

        {{ form.phone_number.errors }}
        {{ form.phone_number.label_tag }}
        {{ form.phone_number }}


        {{ form.email.errors }}
        {{ form.email.label_tag }}
        {{ form.email }}

        {{ form.lease_begin.errors }}
        {{ form.lease_begin.label_tag }}
        {{ form.lease_begin }}

        {{ form.lease_length.errors }}
        {{ form.lease_length.label_tag }}
        {{ form.lease_length }}


        <button type="submit" class="standard-btn create-appointment-btn">
          {% if not object.pk %}
            Add Tenant
          {% else %}
            Update Tenant
          {% endif %}
          <i class="fas fa-pencil-alt"></i>
        </button>
      </form>
    </div>
  </div>

{% endblock %}

{% block page_js %}
<script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script defer type="text/javascript" src="{% static 'tenants/js/calendar.js' %}"></script>
{% endblock %}

tenants/templates/tenants/tenant_list.html
{% extends "base_appointment.html" %}
{% load static %}

{% block title %}Tenants{% endblock title %}

{% block scripts %}
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'appointments/css/table.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'property/css/company_list.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'tenants/css/tenant_list.css' %}">
<!--===============================================================================================-->
	<script defer src="{% static 'appointments/vendor/bootstrap/js/popper.js' %}"></script>
<!--===============================================================================================-->
	<script defer src="{% static 'appointments/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
  <script defer src="{% static 'js/popup_actions.js' %}?v=1.0" type="text/javascript"></script>
  <script defer src="{% static 'js/ajax.js' %}?v=1.0" type="text/javascript"></script>
{% endblock scripts %}

{% block confirm_delete_message %}
Are you sure you want to delete the tenant?
{% endblock confirm_delete_message %}


{% block actions_popup_options %}
<li>
	<a class="action_option delete_object_option delete-trigger" href="#">
		<i class="fa fa-trash delete-trigger" aria-hidden="true"></i>
		<span class="delete-trigger">Delete</span>
	</a>
</li>

<li>
	<a class="action_option delete_object_option" href="#">
		<i class="fa fa-paper-plane" aria-hidden="true"></i>
		<span>Send Renewal Invite</span>
	</a>
</li>
{% endblock actions_popup_options %}

{% block content %}
  <div class="row">
    <div class="limiter">

			<div class="col-sm-12 text-center title-with-paragraph">

				{% if object_list %}
				<h1>{{ company.name }} Tenants</h1>
				{% else %}
				<h1>No Tenants</h1>
				<p>There are currently no tenants.</p>
				{% endif %}
				<a type="button" data-toggle="modal" data-target="#page-options" class="standard-btn">
					<i class="fa fa-ellipsis-h" aria-hidden="true"></i>
				</a>
				<a href="{% url 'tenants:add_tenant' %}?c={{ company.id }}" class="standard-btn">
					Add Tenant
					<i class="fa fa-plus" aria-hidden="true"></i>
				</a>

			</div>

			{# Tenant Actions #}
			<div class="modal fade" id="page-options" tabindex="-1" role="dialog" aria-labelledby="Tenant Options" aria-hidden="true">
			  <div class="modal-dialog modal-dialog-centered" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h3 class="modal-title">Tenant Actions</h3>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
							<ul class="actions-list">
								<li>
									<a href="#" data-dismiss="modal" aria-label="Close" type="button" data-toggle="modal" data-target="#send-mass-text-message">
										<i class="fa fa-comment" aria-hidden="true"></i>
										<span>Send Mass Text Message</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-envelope" aria-hidden="true"></i>
										<span>Send Mass Email Message</span>
									</a>
								</li>
      				</ul>
			      </div>
			    </div>
			  </div>
			</div>

			{# Send Mass Text Message #}
			<div class="modal fade" id="send-mass-text-message" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			  <div class="modal-dialog modal-dialog-centered" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h3 class="modal-title">Send Mass Text Message</h3>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
							<form class="form-horizontal send-mass-message-form" method="post" action="{% url 'tenants:send_mass_message' %}">
				        {% csrf_token %}
								{{ tenant_mass_message_form }}
								<input type="hidden" name="send_text_message" value="True">
								<input type="hidden" name="send_email_message" value="False">
								<input type="hidden" name="company_id" value="{{ company.id }}">
								<button type="submit" class="standard-btn create-appointment-btn">
				          Send
				          <i class="fas fa-pencil-alt"></i>
				        </button>
							</form>
			      </div>
			    </div>
			  </div>
			</div>

			{# Table #}
			{% if object_list %}
      <div class="container-table100">
        <div id="outer_table" class="wrap-table100">
            <div id="inner_table" class="table">

              <div class="table-row header">
								{% for field in fields %}
								<div class="cell">
                  {{ field }}
                </div>
								{% endfor %}
								<div class="cell">
									Actions
								</div>

              </div>

              {% for tenant in object_list %}
              <div class="table-row">

								{# Name #}
                <div class="cell" data-title="Name">
									{% if tenant.ending_soon %}
									<div class="ending_soon_danger">Ending Soon</div>
									{% endif %}
                  {{ tenant.name }}
                </div>

								{# Phone Number #}
								<div class="cell" data-title="Phone Number">
                  <a href="tel:{{ tenant.phone_number }}">{{ tenant.phone_number }}</a>
                </div>

                {# Email #}
								<div class="cell" data-title="Email">
                  <a href="mailto:{{ tenant.email }}">{{ tenant.email }}</a>
                </div>

								{# Lease Begin #}
								<div class="cell" data-title="Lease Begin">
                  {{ tenant.lease_begin }}
                </div>

								{# Lease End #}
								<div class="cell" data-title="Lease End">
                  {{ tenant.lease_end }}
                </div>

								{# Actions #}
								<div class="cell actions" data-title="Actions">
									<button type="button" class="actions-btn actions-trigger" data-object-id="{{ tenant.id }}">
										<i class="fa fa-ellipsis-v actions-trigger" aria-hidden="true"></i>
									</button>
								</div>

								{# Actions for mobile devices #}
								<div class="cell actions-mobile">
									<button type="button" class="standard-btn actions-mobile-btn actions-trigger" data-object-id="{{ tenant.id }}">Actions</button>
								</div>

              </div>
              {% endfor %}

            </div>
        </div>
      </div>
			{% endif %}

			<div class="container">
				<div class="center-children-and-stack">
					<!-- Start Pagination -->
					{% if is_paginated %}
					<ul class="pagination collapse-fix">
						{% if page_obj.has_previous %}
							<li><a href="?page={{ page_obj.previous_page_number }}&c={{ company_id }}">&laquo;</a></li>
						{% else %}
							<li class="disabled"><span>&laquo;</span></li>
						{% endif %}
						{% for i in paginator.page_range %}
							{% if page_obj.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
								<li><a href="?page={{ i }}&c={{ company_id }}">{{ i }}</a></li>
							{% endif %}
						{% endfor %}
						{% if page_obj.has_next %}
							<li><a href="?page={{ page_obj.next_page_number }}&c={{ company_id }}">&raquo;</a></li>
						{% else %}
							<li class="disabled"><span>&raquo;</span></li>
						{% endif %}
					</ul>
					{% endif %}
					<!-- End Pagination -->
				</div>
			</div>
    </div>
  </div>
{% endblock %}

tenants/templates/tenants/tenant_list_ajax_results.html
<div id="inner_table" class="table">

  <div class="table-row header">
    {% for field in fields %}
    <div class="cell">
      {{ field }}
    </div>
    {% endfor %}
    <div class="cell">
      Actions
    </div>

  </div>

  {% for tenant in object_list %}
  <div class="table-row">

    {# Name #}
    <div class="cell" data-title="Name">
      {% if tenant.ending_soon %}
      <div class="ending_soon_danger">Ending Soon</div>
      {% endif %}
      {{ tenant.name }}
    </div>

    {# Phone Number #}
    <div class="cell" data-title="Phone Number">
      <a href="tel:{{ tenant.phone_number }}">{{ tenant.phone_number }}</a>
    </div>

    {# Email #}
    <div class="cell" data-title="Email">
      <a href="mailto:{{ tenant.email }}">{{ tenant.email }}</a>
    </div>

    {# Lease Begin #}
    <div class="cell" data-title="Lease Begin">
      {{ tenant.lease_begin }}
    </div>

    {# Lease End #}
    <div class="cell" data-title="Lease End">
      {{ tenant.lease_end }}
    </div>

    {# Actions #}
    <div class="cell actions" data-title="Actions">
      <button type="button" class="actions-btn actions-trigger" data-object-id="{{ tenant.id }}">
        <i class="fa fa-ellipsis-v actions-trigger" aria-hidden="true"></i>
      </button>
    </div>

    {# Actions for mobile devices #}
    <div class="cell actions-mobile">
      <button type="button" class="standard-btn actions-mobile-btn actions-trigger" data-object-id="{{ tenant.id }}">Actions</button>
    </div>

  </div>
  {% endfor %}

</div>