jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    #example: site/job
    path('', views.index, name='index'),
    path('redirect', views.redirect_user, name='redirect_user'),
    path('thank_you', views.thank_you, name='thank_you'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('customer-register', include('customer_register.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('jobs-admin/', include('jobs_admin.urls')),
    path('addjob/', include('addjob.urls')),
    path('expenses/', include('expenses.urls')),
    path('add-payment/', include('add_payment.urls')),
    path('payment-history/', include('payment_history.urls')),
    path('payments/', include('payment_requests.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('add-house/', include('add_house.urls')),
    path('add-expense/', include('add_expense.urls')),
    path('spreadsheets/', include('csv_generator.urls')),
    path('projects/', include('projects.urls')),
    path('search/', include('search_submit.urls')),
    path('send-data/', include('send_data.urls')),
    path('project-details/', include('project_details.urls')),
    path('customer-payments/', include('customer_payments.urls')),
    path('property/', include('property.urls')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('tenants/', include('tenants.urls')),
    path('leads/', include('leads.urls')),
    path('redirect/', include('redirect.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('product', views.product, name='product'),
    path('contact-sales', views.contact_sales, name='contact_sales'),
    path('contact-support', views.contact_support, name='contact_support'),
    path('privacy-policy', views.privacy_policy, name='privacy_policy'),
    path('terms-and-conditions', views.terms_and_conditions, name='terms_and_conditions'),
]

website/forms.py
from django import forms

class Contact_Sales(forms.Form):
    """
    Allows potential customers to
    contact the sales team
    """
    first_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    phone_number = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))

class Contact_Support(forms.Form):
    """
    Allows a visitor or user
    to contact the support team
    """
    email   = forms.CharField(label='', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    message = forms.CharField(label='', max_length=5000, widget=forms.TextInput(attrs={'placeholder': 'Your message...'}))

website/views.py
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render
from website.forms import Contact_Sales, Contact_Support
from django.core.mail import send_mail
from django.contrib import messages

def home(request):
    #load the template
    template = loader.get_template('website/home.html')
    context = {}

    return HttpResponse(template.render(context, request))

def product(request):
    #load the template
    template = loader.get_template('website/product.html')
    context = {}

    return HttpResponse(template.render(context, request))

def contact_sales(request):
    #load the template
    template = loader.get_template('website/contact_sales.html')
    contact_sales_form = Contact_Sales()
    context = {
        'contact_sales_form': contact_sales_form,
    }

    if request.method == 'POST':
        contact_sales_form = Contact_Sales(data=request.POST)
        if contact_sales_form.is_valid():
            first_name = contact_sales_form.cleaned_data['first_name']
            last_name = contact_sales_form.cleaned_data['last_name']
            email = contact_sales_form.cleaned_data['email']
            phone_number = contact_sales_form.cleaned_data['phone_number']

            message = """
            A demo of Nova One has been requested.\n
            First Name: {first_name}\n
            Last Name: {last_name}\n
            Email: {email}\n
            Phone Number: {phone_number}
            """.format(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone_number=phone_number,
            )

            send_mail(
                'Demo Requested',
                message,
                'no-reply@novaonesoftware.com',
                ['andre.mashraghi@gmail.com'],
                fail_silently=False,
            )

            messages.success(request, 'Thanks! Your demo request has been sent!')
        else:
            messages.error(request, 'Validation Error: Please try again.')
    else:
        contact_sales_form = Contact_Sales()
    return HttpResponse(template.render(context, request))

def contact_support(request):
    if request.method == 'POST':
        contact_support_form = Contact_Support(data=request.POST)
        if contact_support_form.is_valid():
            email = contact_support_form.cleaned_data['email']
            form_message = contact_support_form.cleaned_data['message']

            email_message = """
            A customer has requested support. Please see details below.\n
            Customer Email: {email}\n
            Customer Message: {form_message}
            """.format(
                email=email,
                form_message=form_message,
            )

            send_mail(
                'Customer Support Needed',
                email_message,
                'no-reply@novaonesoftware.com',
                ['andre.mashraghi@gmail.com'],
                fail_silently=False,
            )

            messages.success(request, 'Thanks! Your message has been sent!')
        else:
            messages.error(request, 'Validation Error: Please try again.')
    else:
        raise Http404("Invalid request: Only POST request allowed.")

    template = loader.get_template('404.html')
    return HttpResponse(template.render(request=request))

def privacy_policy(request):
    #load the template
    template = loader.get_template('website/privacy_policy.html')
    context = {}

    return HttpResponse(template.render(context, request))

def terms_and_conditions(request):
    #load the template
    template = loader.get_template('website/terms_and_conditions.html')
    context = {}

    return HttpResponse(template.render(context, request))

website/templates/website/base_generic_website.html
{% load static %}
<!DOCTYPE html>
<html class="{% block html_class %}{% endblock html_class %}" lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <title>{% block title %}{% endblock title %}</title>
      <!-- jQuery -->
      <script
  			  src="http://code.jquery.com/jquery-3.3.1.min.js"
  			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  			  crossorigin="anonymous" async>
      </script>
      <!-- Fonts -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400|Raleway:300" />
      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <!-- Website CSS -->
      <link rel="stylesheet" href="{% static 'website/main.css' %}?v=1.0">
      <!-- Latest compiled and minified JavaScript -->
      <script defer src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>

      {% if request.path == "/" %}
      <script defer src="{% static 'website/main.js' %}"></script>
      {% endif %}

      <!-- Custom -->
      {% block scripts %}
      {% endblock scripts %}
  </head>

  <body class="{% block body_class %}{% endblock body_class %}">
    {% include 'website/navigation.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'website/footer.html' %}
  </body>
</html>

website/templates/website/contact_sales.html
{% extends 'website/base_generic_website.html' %}
{% load static %}

{% block scripts %}
{% endblock scripts %}


{% block content %}
<div id="page-content">
  <main id="main">
    <section id="contact-sales-home-banner" class="home-banner">
      <div class="container-fluid max-width-container">

        <div class="row">
          <div class="col-lg-6 title-p-cta">
            <h1>Tired of Contacting Hundreds of Leads?</h1>
            <p class="description-text">
              NovaOne allows you to painlessly rent out your property faster
              by automating tasks.
            </p>
            <ul class="list-group">
              <li class="list-group-item"><i class="far fa-thumbs-up"></i>Stress-free lead management</li>
              <li class="list-group-item"><i class="far fa-thumbs-up"></i>SMS and email alerts</li>
              <li class="list-group-item"><i class="far fa-thumbs-up"></i>Automated lead qualification</li>
              <li class="list-group-item"><i class="far fa-thumbs-up"></i>Automated appointment scheduling</li>
              <li class="list-group-item"><i class="far fa-thumbs-up"></i>Free live support</li>
            </ul>
          </div>
          <div class="col-lg-6">
            <form id="contact-sales-form" class="standard-webiste-form" action="" method="post">
              {% csrf_token %}
              <div class="form-intro">
                <h2>See A Live Demo Now!</h2>
                <p>
                  See how Nova One can help
                  you easily manage your rental leads.
                </p>
              </div>

              {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{message}}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% if form.errors %}
                <div class="form-messages">
                  <p>Please enter in all data and try again.</p>
                </div>
              {% endif %}

              {{ contact_sales_form }}
              <input class="standard-btn" type="submit" value="See Demo Now!">
              <div class="form-description">
                <p>
                  By clicking “See Demo Now!”, you agree to receive more
                  information about the NovaOne Software Service.
                </p>
              </div>
            </form>
          </div>
        </div>

      </div>

    </section>
  </main>
</div>
{% endblock content %}

website/templates/website/footer.html
{% load static %}

<footer>
  <div class="container-fluid max-width-container">

    <nav class="footer-nav">
      <ul class="footer-nav-menu list-inline">
        <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'website:home' %}">Home</a>
        </li>
        <!-- <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'website:product' %}">Product</a>
        </li> -->
        <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'website:contact_sales' %}">Demo</a>
        </li>
        <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'login' %}">Log In</a>
        </li>
        <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'website:privacy_policy' %}">Privacy</a>
        </li>
        <li class="footer-nav-menu-item list-inline-item">
          <a href="{% url 'website:terms_and_conditions' %}">Terms &amp; Conditions</a>
        </li>
      </ul>
      <div class="logo-container">
        <img src="{% static 'website/images/nova-one-logo.png' %}" alt="Nova One Software">
      </div>
      <p class="copyright">Copyright &copy; <script>document.write(new Date().getFullYear())</script> NovaOne</p>
    </nav>
  </div>
</footer>

website/templates/website/home.html
{% extends 'website/base_generic_website.html' %}
{% load static %}

{% block scripts %}
{% endblock scripts %}


{% block content %}
<div id="page-content">
  <main id="main">
    <section class="home-banner">
      <div class="container-fluid max-width-container">

        <div class="row">
          <div class="col-lg-6 title-p-cta">
            <h1>The Easiest, Fastest Way to Manage Your Rental Leads</h1>
            <p class="description-text">
              Automated lead contact, lead qualification, and appointment scheduling.
              Stress-free, automated lead tracking.
            </p>
            <a href="{% url 'customer_register:customer-register' %}" class="standard-btn">Try It For Free</a>
            <div class="description">
              <p>Already on Nova One? <a href="/accounts/login">Log in</a></p>
            </div>
          </div>
          <figure class="col-lg-6">
            <img src="{% static 'website/images/house-for-rent.png' %}" alt="Construction Workers">
          </figure>
        </div>

      </div>

    </section>

    <section class="counters">
      <div class="container-fluid full-width-container">
        <div class="row">
          <div class="counter col-md-4">
              <span class="text-above">More Than</span>
              <div class="number-wrap">
                <span class="number" data-count-params='{"num_begin": 0, "num_end":100,"duration":1500}'>100</span>
              </div>
              <span class="text-below">Possibilities</span>
          </div>
          <div class="counter col-md-4">
              <span class="text-above">Over</span>
              <div class="number-wrap">
                <span class="number" data-count-params='{"num_begin": 0, "num_end":500,"duration":400}'>500</span><span class="number-suffix">+</span>
              </div>
              <span class="text-below">Rental Properties Tracked</span>
          </div>
          <div class="counter col-md-4">
              <span class="text-above">More Than</span>
              <div class="number-wrap">
                <span class="number" data-count-params='{"num_begin": 0, "num_end":500,"duration":800}'>500</span><span class="number-suffix">+</span>
              </div>
              <span class="text-below">Leads Qualified</span>
          </div>
        </div>
      </div>
    </section>

    <section class="home-second page-section">
      <div class="container-fluid max-width-container">
        <div class="row">

          <div class="col-12">
            <h1 class="p1">
              "NovaOne has expedited our lead process, allowing us to rent to leads before our competitors do."
            </h1>
            <p class="ps-text">
              This is a comment from one of our customers, which we hear <i>a lot</i>.
            </p>
            <p class="description-text">
              Your rental business runs on time, and every minute counts. NovaOne helps you
              stay ahead of the curve by automating tasks.
            </p>
            <p>
              <a href="{% url 'customer_register:customer-register' %}" class="standard-btn">Join For Free</a>
            </p>
          </div>

          <div class="col-12 selling-points">
            <div class="row">

              <div class="col-md icon-title-description">
                <div class="icon">
                  <img src="{% static 'website/images/checklist.png' %}" alt="Checklist">
                </div>
                <h4>Manage</h4>
                <p>
                  Hands-off tracking of incoming leads
                </p>
              </div>

              <div class="col-md icon-title-description">
                <div class="icon">
                  <img src="{% static 'website/images/notification-bell.png' %}" alt="Notification Bell">
                </div>
                <h4>Alerts</h4>
                <p>
                  Recieve SMS and email alerts when qualified leads make appointments
                </p>
              </div>

              <div class="col-md icon-title-description">
                <div class="icon">
                  <img src="{% static 'website/images/organize.png' %}" alt="Organize Diagram">
                </div>
                <h4>24/7 Automated Contact</h4>
                <p>
                  Let NovaOne effortlessly contact and qualify leads for you 24/7
                </p>
              </div>

              <div class="col-md icon-title-description">
                <div class="icon">
                  <img src="{% static 'website/images/house.png' %}" alt="House">
                </div>
                <h4>Automated Scheduling</h4>
                <p>
                  Frustration-free appointment scheduling: set your showing
                  schedule and NovaOne does the rest
                </p>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>

    <section class="home-solutions page-section">
      <div class="container-fluid max-width-container">
        <div class="row">

          <div class="col-12 home-solutions-intro">
            <div class="page-section-title-with-text">
              <h2>
                See How NovaOne Can Help You
              </h2>
              <p class="description-text">
                Watch the video below to see how NovaOne
                can help you easily stay on top of your projects.
              </p>
            </div>
          </div>

          <div class="home-solutions-columns">
            <div class="row">
              <div class="col-lg-7">
                <div class="video-container">
                  <video autoplay playsinline muted loop poster="{% static 'website/images/novaone-video-poster.png' %}" width="100%" height="auto">
										<source src="{% static 'website/videos/novaone.mp4' %}" type="video/mp4">
									</video>
                </div>
              </div>
              <div class="col-lg-5 home-solutions-items">
                <div class="row">
                  <div class="col-md-4 col-lg-12 item-with-title-p">
                    <h4><i class="fas fa-rocket"></i>Rent Faster</h4>
                    <p>NovaOne works all day 7 days a week to make sure your property gets rented.</p>
                  </div>
                  <div class="col-md-4 col-lg-12 item-with-title-p">
                    <h4><i class="fas fa-robot"></i>Automate Qualification</h4>
                    <p>Painlessly pre-qualify tenants automatically with NovaOne.</p>
                  </div>
                  <div class="col-md-4 col-lg-12 item-with-title-p">
                    <h4><i class="far fa-calendar-alt"></i>Reduce No-Shows</h4>
                    <p>Effortlessly reduce appointment no-shows with NovaOne.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="home-sign-up page-section">
      <div class="container-fluid max-width-container">
        <div class="row">
          <div class="col-md-12">
            <img src="{% static 'website/images/agreement.png' %}" alt="Sign Up">
            <h2>Sign Up Free</h2>
            <p class="description-text">
              Sign up for free today and get all features, free updates, and unparalleled support.
            </p>
            <a href="{% url 'customer_register:customer-register' %}" class="standard-btn">Start For Free</a>
          </div>
        </div>
      </div>
    </section>

  </main>
</div>
{% endblock content %}

website/templates/website/navigation.html
{% load static %}

<nav id="navbar" class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container-fluid max-width-container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'website/images/nova-one-logo.png' %}" alt="NovaOne Software">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'website:product' %}">Product</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'website:contact_sales' %}">Demo</a>
        </li>
        <li class="nav-item">
          <a class="standard-btn" href="{% url 'customer_register:customer-register' %}">Try Free</a>
        </li>
      </ul>
    </div>
  </div>
</nav>