csv_generator/urls.py
from django.urls import path
from . import views

app_name = 'csv_generator'

urlpatterns = [
    path('all-data-spreadsheet', views.all_data_spreadsheet, name='all_data_spreadsheet'),
    path('project-details-spreadsheet', views.project_details_spreadsheet, name='project_details_spreadsheet'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    #example: site/job
    path('', views.index, name='index'),
    path('redirect', views.redirect_user, name='redirect_user'),
    path('thank_you', views.thank_you, name='thank_you'),
]

project_details/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:house_id>', views.project_details, name='project_details'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('customer-register', include('customer_register.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('jobs-admin/', include('jobs_admin.urls')),
    path('addjob/', include('addjob.urls')),
    path('expenses/', include('expenses.urls')),
    path('add-payment/', include('add_payment.urls')),
    path('payment-history/', include('payment_history.urls')),
    path('payments/', include('payment_requests.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls')),
    path('add-house/', include('add_house.urls')),
    path('add-expense/', include('add_expense.urls')),
    path('spreadsheets/', include('csv_generator.urls')),
    path('projects/', include('projects.urls')),
    path('search/', include('search_submit.urls')),
    path('send-data/', include('send_data.urls')),
    path('project-details/', include('project_details.urls')),
    path('customer-payments/', include('customer_payments.urls')),
    path('property/', include('property.urls')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('tenants/', include('tenants.urls')),
    path('leads/', include('leads.urls')),
    path('redirect/', include('redirect.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_details/views.py
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import user_passes_test
from project_management.decorators import customer_and_staff_check
from send_data.forms import Send_Data
from jobs.models import House, Job
from expenses.models import Expenses
from expenses.forms import Edit_Expense
from jobs_admin.forms import Edit_Job
from django.core.paginator import Paginator
from itertools import chain

@user_passes_test(customer_and_staff_check, login_url='/accounts/login/')
def project_details(request, house_id):
    #get current user
    current_user = request.user

    #get forms and template
    send_data_form = Send_Data()
    edit_expense_form = Edit_Expense(user=current_user)
    edit_job_form = Edit_Job(user=current_user)
    template = loader.get_template('project_details/project_details.html')

    context = {
        'current_user': current_user,
        'send_data_form': send_data_form,
        'edit_job_form': edit_job_form,
        'edit_expense_form': edit_expense_form,
    }

    if house_id:
        #get house
        house = (
            House.objects
            .filter(pk=house_id)
            .add_budget_balance()
            .add_potential_profit()
        )[0]

        approved_jobs = Job.objects.filter(house=house, approved=True).add_balance().order_by('job_type')

        expenses = Expenses.objects.filter(house=house)
        expenses_and_jobs_list = list(chain(expenses, approved_jobs))
        paginator = Paginator(expenses_and_jobs_list, 25) #25 items per page

        page = request.GET.get('page')
        expenses_and_jobs = paginator.get_page(page)

        #add info to the context dictionary
        context['address'] = house.address
        context['house_id'] = house.id
        context['expenses_and_jobs'] = expenses_and_jobs
        context['budget_balance'] = house.budget_balance
        context['budget_balance_degree'] = house.budget_balance_degree
        context['total_spent'] = house.total_spent
        context['purchase_price'] = house.purchase_price
        context['after_repair_value'] = house.after_repair_value
        context['potential_profit'] = house.potential_profit
        context['post_from_url'] = request.build_absolute_uri()

    return HttpResponse(template.render(context, request))

project_details/templates/project_details/project_details.html
{% extends 'logged_in_customer.html' %}

{% load humanize %}
{% load static %}
{% load jobs_admin_group_check %}
{% load class_tag %}

{% block page_title %}{{ address }}{% endblock page_title %}
{% block button_with_title %}<a href="#" class="round-btn solid-round-btn send-post-on-click" data-csrfmiddlewaretoken="{{ csrf_token }}" data-house-id="{{ house_id }}" data-url="{% url 'csv_generator:project_details_spreadsheet' %}" name="generate_spreadsheet">Generate Spreadsheet</a>{% endblock button_with_title %}

{% block scripts %}
<script type="text/javascript" src="{% static 'project_details/project_details.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<div id="spreadhseet-hidden-element" style="display: none;"></div>
<div class="white-block" id="project_details">

  <div class="number-circle-container">
    <h6 class="detail-heading">Budget</h6>
    <div id="activeBorder" class="active-border">
        <div id="circle" class="circle">
            <span class="prec {{ budget_balance_degree }}" id="prec">0%</span>
        </div>
    </div>
    <div class="detail-text-container">
      <span class="detail-value">${{ budget_balance|intcomma }}</span>
    </div>
  </div>

  <div class="row margin-bottom">
    <div class="col-lg-6">
      <div class="col-inner">
        <h6 class="detail-heading">Purchase Price</h6>
        <span class="detail-value">${{ purchase_price|intcomma }}</span>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="col-inner">
        <h6 class="detail-heading">Selling Price</h6>
        <span class="detail-value">${{ after_repair_value|intcomma }}</span>
      </div>
    </div>
  </div>

  <div class="row margin-bottom">
    <div class="col-lg-6">
      <div class="col-inner">
        <h6 class="detail-heading">Total Spent</h6>
        <span class="detail-value">${{ total_spent|intcomma }}</span>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="col-inner">
        <h6 class="detail-heading">Potential Profit</h6>
        <span class="detail-value">${{ potential_profit|intcomma }}</span>
      </div>
    </div>
  </div>

</div>

<div id="expenses-and-jobs">
  {% if expenses_and_jobs %}
    {% for item in expenses_and_jobs %}
      {% ifchanged %}
      <h2 class="sub-title">
        {% if item|get_class == 'Job' %}
          {{ item.job_type }}
        {% else %}
          Expenses & Approved Jobs
        {% endif %}
      </h2>
      <div class="item-headings-wrapper container-fluid">
        <ul class="item-headings row">
          <div class="col col-sm-6">
            <li>Status</li>
            <li class="second-heading">
              {% if item|get_class == 'Expenses' %}
                Type
              {% else %}
                Company
              {% endif %}
            </li>
          </div>
          <div class="col col-sm-4">
            <li class="contract_link">Contract Link</li>
            <li>
              Submitted
            </li>
          </div>
          <div class="col col-sm-2">
            <li>Amount</li>
          </div>
        </ul>
      </div>
      {% endifchanged %}

      {# Item Options Forms #}
      {% if current_user|in_group:'Customers' %}
      <div class="option-forms">
        {% if item|get_class == 'Expenses' %}
          {% include 'includes/forms/delete_expense.html' %}
        {% else %}
          {% include 'includes/forms/reject_job.html' %}
        {% endif %}

      </div>
      <div class="popup-forms">
        {% if item|get_class == 'Expenses' %}
          {% include 'includes/forms/edit_expense.html' %}
        {% else %}
          {% include 'includes/forms/edit_job.html' %}
        {% endif %}
        <ul class="mobile-option-icons popup animated bounceInUp">

          <li>
            {% if item|get_class == 'Expenses' %}

              {% include 'includes/option_items/mobile_options_expense.html' %}

            {% else %}

              {% include 'includes/option_items/mobile_options_job.html' %}

            {% endif %}
          </li>

        </ul>
      </div>
      {% endif %}

      <div class="item-container">
        <div class="container-fluid">
          <div class="row">
            <div class="info-group col col-sm-6">
              <ul>
                <li>
                  {# Status #}
                  {% if item|get_class == 'Expenses' %}
                    <div class="status expense">Expense</div>
                  {% elif item|get_class == 'Job' and item.balance1 > 0 %}
                    <div class="status active">Active Job</div>
                  {% else %}
                    <div class="status approved">Job</div>
                  {% endif %}
                </li>
                <span class="info-title">
                  {% if item|get_class == 'Expenses' %}
                    Expense Type
                  {% else %}
                    Company
                  {% endif %}
                </span>
                <li class="info-1">
                  {{ item.expense_type }}
                  {{ item.company }}
                </li>
                <hr>
              </ul>
            </div>
            <div class="info-group col col-sm-4">
              <ul>
                <span class="info-title">Contract</span>
                <li class="info-2">
                  <a rel="noopener noreferrer" target="_blank" href="{{ item.document_link.url }}">View Contract</a>
                </li>
                <hr>
                <span class="info-title">Submitted</span>
                <li class="info-3">
                  {{ item.submit_date|date:'M j, Y' }}
                  {{ item.start_date|date:'M j, Y' }}
                </li>
                <hr>
              </ul>
            </div>
            <div class="info-group col col-sm-2">
              {% if current_user|in_group:'Customers' %}
              <ul>
                <span class="info-title">Amount</span>
                <li class="info-4">
                  ${{ item.amount|intcomma }}
                  {{ item.start_amount|intcomma }}
                </li>
                <hr>
                {# Mobile Option Buttons #}

                <span class="info-title">Options</span>
                <div class="item-options-toggle-mobile">
                  <button class="item-options-toggle-mobile-btn" type="button" name="item-options-toggle-mobile-btn">
                    <i class="fas fa-ellipsis-h"></i>
                  </button>
                </div>

                {# Desktop Options #}
                <div class="item-options-dropdown dropdown">

                  <a class="item-options-toggle dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-ellipsis-v"></i>
                  </a>
                  {% if item|get_class == 'Expenses' %}
                    {% include 'includes/option_items/desktop_options_expense.html' %}
                  {% else %}
                    {% include 'includes/option_items/desktop_options_job.html' %}
                  {% endif %}

                </div>
              </ul>
              {% endif %}
            </div>
          </div>
        </div>
      </div> <!-- /.item-container -->
    {% endfor %}
  </div>
  {% endif %}

  {% if expenses_and_jobs.has_other_pages %}
  <ul class="pagination">
    {% if expenses_and_jobs.has_previous %}
      <li><a href="?page={{ expenses_and_jobs.previous_page_number }}"><i class="fas fa-angle-left"></i></a></li>
    {% else %}
      <li class="disabled"><span><i class="fas fa-angle-left"></i></span></li>
    {% endif %}
    {% for i in expenses_and_jobs.paginator.page_range %}
      {% if expenses_and_jobs.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if expenses_and_jobs.has_next %}
      <li><a href="?page={{ expenses_and_jobs.next_page_number }}"><i class="fas fa-angle-right"></i></a></li>
    {% else %}
      <li class="disabled"><span><i class="fas fa-angle-right"></i></span></li>
    {% endif %}
  </ul>
  {% endif %}
{% endblock content %}